<?php

namespace AppBundle\Repository;

/**
 * datauserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class datauserRepository extends \Doctrine\ORM\EntityRepository
{
}
